# Generated by Django 5.1.5 on 2025-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="firebase_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
