# Generated by Django 5.1.5 on 2025-02-10 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0003_alter_usuario_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="perfil",
            field=models.ForeignKey(
                default=3,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registros.perfil",
            ),
        ),
    ]
