# Generated by Django 5.1.5 on 2025-02-13 00:46

import links.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="expires_at",
            field=models.DateTimeField(
                default=links.models.ShortenedURL.get_expiration_date
            ),
        ),
    ]
